mq:
  image: rabbitmq:3.5.6-management
  expose:
    - "5672"
    - "15672"
  ports:
    - 5672:5672
    - 15672:15672
  environment:
    RABBITMQ_DEFAULT_USER: "admin"
    RABBITMQ_DEFAULT_PASS: "admin"

db:
  image: mongo:3
  expose:
    - "27017"

producer:
  build: producer/.
  ports:
    - "8080:8080"
  environment:
    RABBIT_URL: "mq"
  links:
    - mq

consumer:
  build: consumer/.
  ports:
    - 3000:3000
  environment:
    PORT: 3000
    RABBIT_URL: "amqp://admin:admin@mq:5672"
    MONGODB_URL: "mongodb://db:27017/logs"
    EXCHANGE: "logs"
  links:
    - producer
    - mq
    - db
    

